#ifndef MARGOT_OP_STRUCTURE_H
#define MARGOT_OP_STRUCTURE_H

#include <string>
#include <unordered_map>
#include <margot/operating_point.hpp>


/**
 * WARNING:
 * This file is autogenerated from the "margotcli" utility function.
 * Any changes to this file might be overwritten, thus in order to 
 * perform a permanent change, please update the configuration file 
 * and re-generate this file. 
 */ 


namespace margot {

	namespace sleeping {

		// Name of the software knobs
		enum class Knob : margot::field_name_t {
			PARAM1 = 0,
			PARAM2 = 1,
			PARAM3 = 2,
		};

		// Name of the metrics of interest
		enum class Metric : margot::field_name_t {
			ERROR = 0,
			THROUGHPUT = 1,
		};

	} // namespace sleeping

} // namespace margot

#endif // MARGOT_OP_STRUCTURE_H

