#include <margot_op_struct.hpp>
#include <margot/operating_point.hpp>



/**
 * WARNING:
 * This file is autogenerated from the "margotcli" utility function.
 * Any changes to this file might be overwritten, thus in order to 
 * perform a permanent change, please update the configuration file 
 * and re-generate this file. 
 */ 


namespace margot {

	namespace sleeping {


		operating_points_t op_list = {
			{ // Operating Point 1
				{ 1, 2, 3 }, // The software knobs
				{ 6, 6 }, // The metrics of interest
			}
		};

	} // namespace sleeping

} // namespace margot

